# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10525f24e21a5ace7976e308d340b101517862c8babd7b606c6788b16868966ba71a52e6143172b7a8062383436d3de452f097152bf92ec1ea2459422db3fa48

test:
  secret_key_base: fa5885f29dc18d6b75edd92165c46e9970614a55e98d4678fa985b298edef55fa30dbc46c6552185d7b49080dc01a27281a51e54eed26b6b6dc56331020582ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
